version: "3.6"
  #docker run -p 8080:8080 cowserver:1.0

services:
  web:
    container_name: myapp
    restart: always
    environment:
      - LORA_MONGODB_HOST=mongo
      - LORA_MONGODB_DATABASE=lora-app
      - ES_HOST=es01
      - ELASTIC_URL=http://es01:9200
      - NODE_ENV=local
    ports:
      - "8080:8080"
    build: .    
    links:
      - es01
    depends_on:
      - es01  
      - kib01
    networks:
      - myappnetwork
  mongo: 
    container_name: mongo
    image: mongo
    volumes:
      - ./todo-mongodb-data:/var/lib/mongodb
    ports:
      - "27017:27017"
    
    networks:
      - myappnetwork
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - myappnetwork
  kib01:
    image: docker.elastic.co/kibana/kibana:7.17.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - myappnetwork
volumes:
  data01:
    driver: local
networks:
  myappnetwork:
    driver: bridge
    external : false  
    name: custom_network 
                                                                                                                                                                            
